#!/usr/bin/perl

require IDGEN;
use IDGEN;

require CARD;
use CARD;

my $n = (@ARGV) ? shift @ARGV : die "Must specify arg\n";

my $vars = [];
for(my $i=0; $i<$n; ++$i) {
    push @{$vars}, &IDGEN::gen_id();
}

print "SC ENCODING:\n";
$csstr = &CARD::gen_sc_atmost1($vars);
print "$csstr";
print "\n\n";

print "BDD EQUIV ENCODING:\n";
my $csstr = &CARD::gen_bdd_atmostN($vars, 1);
print "$csstr";
print "\n\n";

&CARD::bdd_set_mode(0);
print "BDD IMPLIC ENCODING:\n";
my $csstr = &CARD::gen_bdd_atmostN($vars, 1);
print "$csstr";

1;

