### Makefile --- 

## Author:   jpms
## Keywords: 
## Revision: $Id$.
## Copyright (c) 2007, Joao Marques-Silva

SRCS= $(wildcard *.c)

CTRGT= maxsatz14bis+fl.c

TRGT= maxsatz

all: $(TRGT)

$(TRGT): $(SRCS)
	gcc -o $(TRGT) $(CTRGT)

clean:
	@rm -f *.o a.out $(TRGT)

### Makefile ends here
