#!/bin/csh
set bdir = $argv[2]
set name = $argv[1]

set ref_log = "coaching/features/$name"

foreach bench ($bdir/*)
	echo "Obtaining features from " $bench
	./getfeatures $bench > $ref_log.`basename $bench`."features"
end

