#!/bin/csh

if ($# < 5) then
    echo "Usage: $0 <tool> <alg> <enc> <opts> <dir> <ref>"
    echo "For tools other than msuncore, alg='', enc='', opts=''"
    exit
endif

set tool = $argv[1]
set alg = $argv[2]
set enc = $argv[3]
set opts = "$argv[4]"
#echo "$opts"; exit;

set bdir = $argv[5]
set ref = $argv[6]

set timeout = 1000
set memout = 2000000

set msu_log = "Results/$tool-a$alg-e$enc-$ref.log"

rm -f $msu_log
set flist = `ls $bdir/*.cnf $bdir/*.txt $bdir/*.dimacs $bdir/*.seq`
#echo $flist; exit

touch $msu_log
foreach bench ($flist)
    echo "Running $tool on $bench..."
    echo "./scripts/run$tool $alg $bench $enc "$opts" $timeout $memout >> $msu_log"
    #exit
    #if ($opts == '') then
    #	./scripts/run$tool $alg $bench $enc $timeout $memout >> $msu_log
    #else
	./scripts/run$tool $alg $bench $enc "$opts" $timeout $memout >> $msu_log
    #endif
end
#echo $flist

# jpms
