#!/usr/bin/perl
$extension = '.bak';
 LINE: while (<>) {
     if ($ARGV ne $oldargv) {
	 if ($extension !~ /\*/) {
	     $backup = $ARGV . $extension;
	 }
	 else {
	     ($backup = $extension) =~ s/\*/$ARGV/g;
	 }
	 rename($ARGV, $backup);
	 open(ARGVOUT, ">$ARGV");
	 select(ARGVOUT);
	 $oldargv = $ARGV;
     }
     chomp;
     if ($_ eq '') { next; }
     print "$_\n";
}
select(STDOUT);
