#!/bin/csh

set inpdir = $1
set outdir = $2
#echo $inpdir ; echo $outdir ; exit

foreach f (`ls $inpdir/*.gen`)
    #echo $f:r:t
    ./runships -yRa1 $f
    mv rpoly.pbo $outdir/$f:r:t.pbo
    pb2opb $outdir/$f:r:t.pbo > $outdir/$f:r:t.opb
    opb2pmcnf $outdir/$f:r:t.opb > $outdir/$f:r:t.pmcnf
    rm -f $outdir/$f:r:t.opb $outdir/$f:r:t.pbo
end

# jpms
