#!/usr/bin/perl

my @tools = ();
while(<>) {
    #print;
    if (m/(\S+)\s+(\S+)/) {
	my $tname = $1;
	my $talias = $2;
	push @tools, $tname;
	#print "@tools";
    }
}
{ $" = "\n"; print "@tools\n"; $" = ' '; }

1;

# jpms
