#!/bin/csh

if ($# < 2) then
    echo "Usage: $0 <tool> <dir> <ref>"
    exit
endif

set bdir = $argv[1]
set ref = $argv[2]


set msu_log = "Results/numcls-$ref.log"

rm -f $msu_log

touch $msu_log
foreach bench ($bdir/*.cnf $bdir/*.txt $bdir/*.dimacs $bdir/*.seq)
    echo "Running numcls on $bench..."
    ./scripts/numcls $bench >> $msu_log
end

# jpms
