#!/usr/bin/perl

use strict;

my $outfile = 'msudist';
my $msu = 'msuncore';

my @pms = qw(UTILS IDGEN CARD CLUTILS CLSET CLMSET MSUDS MSUTILS SATUTILS msu1 msu2 msu3 msu4);

`rm -f $outfile`;
`touch $outfile`;
`cat $msu >> $outfile`;
foreach my $pm (@pms) {
    `cat $pm.pm >> $outfile`;
    `echo "" >> $outfile`;
}
`echo "" >> $outfile`;

`perl -pi -e 's/require UTILS;//' $outfile`;
`perl -pi -e 's/import UTILS;//' $outfile`;
`perl -pi -e 's/^use UTILS.+//' $outfile`;

`perl -pi -e 's/require IDGEN;//' $outfile`;
`perl -pi -e 's/import IDGEN;//' $outfile`;
`perl -pi -e 's/^use IDGEN.+//' $outfile`;

`perl -pi -e 's/require CARD;//' $outfile`;
`perl -pi -e 's/import CARD;//' $outfile`;

`perl -pi -e 's/require CLUTILS;//' $outfile`;
`perl -pi -e 's/import CLUTILS;//' $outfile`;
`perl -pi -e 's/^use CLUTILS.+//' $outfile`;

`perl -pi -e 's/require CLSET;//' $outfile`;
`perl -pi -e 's/import CLSET;//' $outfile`;

`perl -pi -e 's/require CLMSET;//' $outfile`;
`perl -pi -e 's/import CLMSET;//' $outfile`;

`perl -pi -e 's/require MSUDS;//' $outfile`;
`perl -pi -e 's/import MSUDS;//' $outfile`;

`perl -pi -e 's/require MSUTILS;//' $outfile`;
`perl -pi -e 's/import MSUTILS;//' $outfile`;

`perl -pi -e 's/require SATUTILS;//' $outfile`;
`perl -pi -e 's/import SATUTILS;//' $outfile`;
`perl -pi -e "s/\\.\\/mscore/\\.\\/msub/" $outfile`;
`perl -pi -e "s/mscore\\.log/___msub.tmp___/" $outfile`;

`perl -pi -e 's/require msu1;//' $outfile`;
`perl -pi -e 's/import msu1;//' $outfile`;

`perl -pi -e 's/require msu2;//' $outfile`;
`perl -pi -e 's/import msu2;//' $outfile`;

`perl -pi -e 's/require msu3;//' $outfile`;
`perl -pi -e 's/import msu3;//' $outfile`;

`perl -pi -e 's/require msu4;//' $outfile`;
`perl -pi -e 's/import msu4;//' $outfile`;

`chmod 700 $outfile`;

1;

