#!/usr/bin/perl

my $bench = shift @ARGV;

$bench =~ m/[^\/]+\/([^\/\s]+$)/;
$inst = $1;

my $ncls = &get_num_cls($bench);
my $prtstr = sprintf("%-35s  %d", $inst, $ncls);
print "$prtstr\n";

1;

sub get_num_cls() {
    my $fname = shift;
    open (BENCHF, "<$fname") || die "Unable to open bench file $fname\n";
    my $ncls = -1;
    while (<BENCHF>) {
	if (m/p\s+cnf\s+(\d+)\s+(\d+)/) { $ncls = $2; last; }
    }
    #print "Num cls: $ncls\n";
    close(BENCHF);
    return $ncls;
}

# jpms
