#!/bin/csh

if ($#argv != 2) then
   echo "usage: '$0' directory result-file-name"
   exit(0)
endif

set bdir = $argv[1]
set ref = $argv[2]

set msu_log = "Results/msuncore-$ref.log"
set msz_log = "Results/maxsatz-$ref.log"

rm -f $msu_log $msz_log

touch $msu_log
foreach bench ($bdir/*)
    ./scripts/runmsuncore 2 $bench >> $msu_log
end

touch $msz_log
foreach bench ($bdir/*)
    ./scripts/runmaxsatz $bench >> $msz_log
end

