#!/bin/csh

set bdir = $argv[1]
set ref = $argv[2]

set msu_log = "Results/msuncore-$ref.log"
set msz_log = "Results/maxsatz-$ref.log"

rm -f $msu_log $msz_log

touch $msu_log
foreach bench ($bdir/*)
    ./runmsuncore 2 $bench >> $msu_log
end

touch $msz_log
foreach bench ($bdir/*)
    ./runmaxsatz $bench >> $msz_log
end

