#!/bin/csh

set bdir = $argv[1]
set ref = $argv[2]

set ref_log = "Results/numcls-$ref.log"
set msu_log = "Results/msuncore-$ref.log"
set msz_log = "Results/maxsatz-$ref.log"

rm -f $ref_log $msu_log $msz_log

touch $ref_log
foreach bench ($bdir/*)
    ./scripts/numcls $bench >> $ref_log
end

touch $msu_log
foreach bench ($bdir/*)
    ./runmsuncore $bench 1000 >> $msu_log
end

touch $msz_log
foreach bench ($bdir/*)
    ./runmaxsatz $bench 1000 >> $msz_log
end

