#!/bin/csh

if ($# < 5) then
    echo "Usage: $0 <tool> <alg> <enc> <dir> <ref>"
    echo "For tools other than msuncore, alg='', enc=''"
    exit
endif

set tool = $argv[1]
set alg = $argv[2]
set enc = $argv[3]

set bdir = $argv[4]
set ref = $argv[5]

set timeout = 1000
set memout = 2000000

set msu_log = "Results/$tool-a$alg-e$enc-$ref.log"

rm -f $msu_log

touch $msu_log
foreach bench ( `ls -S $bdir/*.seq` )
    if ($bench == "$bdir/b15-bug-fourvec-gate-0.dimacs.seq") then
	echo "Skipping $bench ..."
    else
       echo "Running $tool on $bench..."
       #echo "./scripts/run$tool $alg $bench $enc $timeout $memout >> $msu_log"
       ./scripts/run$tool $alg $bench $enc $timeout $memout >> $msu_log
    endif
end

# jpms
